### ISSUE TITLE
Form input issues

### ISSUE THREAD

**Issue by darin-invitae** [simona1/Restaurant-Hopping#1]
https://github.com/simona1/Restaurant-Hopping/blob/ec29abed008d1cb0acac868fd1480a3b6ae2bd86/src/client/PlaceForm.js#L16

- Form submission is not being blocked.  As a consequence the page reloads (clearing input) if the user presses return.
- The action to call the API is being dispatched effectively on every keystroke via `onChange`.  Inputs of the this type should really be being debounced so as to not spam the server or lock up the client.
- Search only appears to work when entering city names.  While it would certainly be nice to be able to search by address as well, at a minimum (as a user) I would expect the UI to clue me to the fact that I must enter a city only.

**Comment by simona1** [comment]
Thank you for pointing that out. 
Regarding the use of `form`, initially I thought that a `form` may be appropriate here. When I changed my mind later, I forgot to remove it. I have fixed that issue, and changed the `placeholder` message to a more appropriate one. Will add a`TODO` for allowing a search by address.
Finally, I also added `debounce` to handle the potential server spamming.

**Comment by darin-invitae** [comment]
Looks good.
