### ISSUE TITLE
Unable to use Yarn

### ISSUE THREAD

**Issue by darin-invitae** [simona1/Restaurant-Hopping#2]
I was not able to get things working per the instructions in `readme` as the version of node being installed here is `4.2.6` and the semver for Yarn is `"^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"`.

I was able to get the app working fine locally though so it would seem vagrant is not required.

https://github.com/simona1/Restaurant-Hopping/blob/7f0fb435afb8dee1d856edf145c8845ccb9014d3/Vagrantfile#L21

**Comment by simona1** [comment]
You are right that Vagrant is not required. I like to build my apps in an isolated environment, hence the use of the Vagrant VM container.
