### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by darin-invitae** [simona1/Restaurant-Hopping#4]
Caching these calls is smart.   A more formalized approach maybe to use the memoize pattern.

Also, what is the reasoning behind executing the callback via `setTimeout`?

https://github.com/simona1/Restaurant-Hopping/blob/7f0fb435afb8dee1d856edf145c8845ccb9014d3/src/client/actions/updateLocationQuery.js#L13

**Comment by simona1** [comment]
Do you mean using the Lodash `memoize` function? 
As for executing the callback via `setTimeout`, I wanted this function to be consistently asynchronous.
I would have used `setImmediate`, but it is not yet widely supported.

**Comment by darin-invitae** [comment]
Lodash memoize is fine, or from a similar Functional library; or just spin up your own -- at it's heart memoize is just a closure around what you basically have already.

**Comment by simona1** [comment]
I have refactored the code to use memoize for caching the API calls.
