### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by darin-invitae** [simona1/Restaurant-Hopping#5]
The `key` attribute here is based on the passed in `place.id`.  This means that each child has identical keys when they should be unique.  This leads to inefficient rendering in React and could be the source of hard-to-find glitches as app complexity grows.

https://github.com/simona1/Restaurant-Hopping/blob/7f0fb435afb8dee1d856edf145c8845ccb9014d3/src/client/PlacesList.js#L29

**Comment by simona1** [comment]
I agree. The key error was associated with the star `materialize-icon`, `<i>` used to represent the ranking. I debated using the Lodash `uniqueId` function to generate a unique hash for these, but that would also mean that they'd be re-rendered. 
As to the `<li>` elements, each `place-id` is unique based on google-maps-api  documentation
https://developers.google.com/places/place-id
so these respect React best practices.

**Comment by darin-invitae** [comment]
Yes, random ids (uniqueID) would be a bad choice due to re-rendering.  This is a situation where using the index as part of the key is probably appropriate.  Since each `place.id` is unique and the order of the Stars never changes, then something like this would work
```
key={`${id}-${i}`}
```

**Comment by simona1** [comment]
Makes sense. Done.

**Comment by darin-invitae** [comment]
Unfortunately, this change broke your tests ;)

**Comment by simona1** [comment]
Oops, forgot to update the snapshot :) Will do that later today when I have a chance to refactor the code some more.
